forum/Models/ViewModels/LoginViewModel.cs
using System;
using forum.Models;
using System.Collections.Generic;
using Microsoft.AspNetCore.Http;
using System.Linq;
using System.ComponentModel.DataAnnotations;

namespace forum.Models.ViewModels
{
    public class LoginViewModel
    {
		public string Username { get; set; }
		public string Password { get; set; }

    }
}

forum/Models/ViewModels/RegisterViewModel.cs
using System;
using forum.Models;
using System.Collections.Generic;
using Microsoft.AspNetCore.Http;
using System.Linq;
using System.ComponentModel.DataAnnotations;

namespace forum.Models.ViewModels
{
    public class RegisterViewModel
    {
		/*[Required]
		[EmailAddress]
		[Display(Name = "Email")]
		public string Email { get; set; }*/

		[Required]
		[Display(Name = "Username")]
		public string Username { get; set; }

		[Required]
		[DataType(DataType.Password)]
		[Display(Name = "Password")]
		public string Password { get; set; }

		[DataType(DataType.Password)]
		[Display(Name = "Confirm password")]
		[Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
		public string ConfirmPassword { get; set; }
        public IFormFile Picture { get; set; }

    }
}

forum/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

using forum.Services;
using forum.Models.ViewModels;
using forum.Models;
using forum.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using System.IO;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;

namespace forum.Controllers
{
    public class HomeController : Controller
    {
		private readonly IDBService _dbService;
        private readonly ForumContext _context;
		private readonly UserManager<Person> _userManager;
		private readonly SignInManager<Person> _signInManager;
        private readonly IHostingEnvironment _environment;

        public HomeController(UserManager<Person> userManager, SignInManager<Person> signInManager, ForumContext context, IDBService dbService, IHostingEnvironment environment)
		{
			_dbService = dbService;
            _context = context;
			_userManager = userManager;
			_signInManager = signInManager;
            _environment = environment;
		}

		private Task<Person> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        public async Task<IActionResult> Index()
        {
			var user = await GetCurrentUserAsync();

            var model = new ThreadsViewModel()
            {
                Threads = _context.Threads.Include(c => c.Person).AsNoTracking(),
                Posts = _context.Posts.Include(c => c.Person).OrderByDescending(c => c.Created).AsNoTracking(),
                People = _dbService.GetAllUsers().OrderByDescending(c => c.Joined),
                Person = user
            };

            return View(model);
        }

		public IActionResult Register()
		{

			return View();
		}

		[HttpPost]
		public async Task<IActionResult> Register(RegisterViewModel model)
		{
            var user = new Person { UserName = model.Username, Picture = UploadImage(model.Picture), Joined = DateTime.Now.ToString() };
			IdentityResult result = await _userManager.CreateAsync(user, model.Password);
			if (result.Succeeded)
			{
                //return RedirectToAction("Index");
                TempData["path"] = UploadImage(model.Picture);
                return View();
			}
			else
			{
				return View();
			}
		}

		public string UploadImage(IFormFile Picture)
		{
			if (Picture == null)
			{
				return "http://placehold.it/500x500";
			}

			var uploadFolder = "uploads";
			var uploads = Path.Combine(_environment.WebRootPath, uploadFolder);

			using (var fileStream = new FileStream(Path.Combine(uploads, Picture.FileName), FileMode.Create))
			{
				Picture.CopyTo(fileStream);
			}

            return string.Concat(uploadFolder, "/", Picture.FileName);
		}

		public IActionResult Login()
		{
			return View();
		}

		[HttpPost]
		public async Task<IActionResult> Login(LoginViewModel model)
		{
            Microsoft.AspNetCore.Identity.SignInResult result = await _signInManager.PasswordSignInAsync(model.Username, model.Password, isPersistent: true, lockoutOnFailure: false);
			if (result.Succeeded)
			{
				return RedirectToAction("Index");
			}
			else
			{
				return View();
			}
		}

		[HttpPost]
		public async Task<IActionResult> LogOff()
		{
			await _signInManager.SignOutAsync();
			return RedirectToAction("Index");
		}

        public IActionResult Error()
        {
            return View();
        }
    }
}

forum/Controllers/ThreadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

using forum.Services;
using forum.Models.ViewModels;
using forum.Models;
using forum.Data;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;

namespace forum.Controllers
{
	public class ThreadController : Controller
	{
		private readonly ForumContext _context;
		private readonly IDBService _dbService;
		private readonly UserManager<Person> _userManager;
        private readonly IHostingEnvironment _environment;

		public ThreadController(UserManager<Person> userManager, IDBService dbService, ForumContext context, IHostingEnvironment environment)
		{
			_userManager = userManager;
			_dbService = dbService;
			_context = context;
            _environment = environment;
		}

		private Task<Person> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

		public IActionResult Index()
		{
			var model = new ThreadsViewModel()
			{
				Threads = _dbService.GetAllThreads()
			};

			return View(model);
		}

		[HttpGet]
		public IActionResult GetThread(int id)
		{

			var model = new ThreadsViewModel()
			{
				Thread = _dbService.GetThread(id),
				Posts = _context.Posts.Where(i => i.ThreadID == id).Include(c => c.Person).AsNoTracking(),
			};

			return View(model);
		}

		public IActionResult AddThread()
		{

			return View();
		}

		[HttpPost]
		public async Task<IActionResult> AddThread(ThreadsViewModel model)
		{
			var user = await GetCurrentUserAsync();
			var userID = user?.Id;

			if (ModelState.IsValid)
			{

				var newThread = new Thread()
				{
					PersonID = userID,
					Subject = model.Thread.Subject,
					Text = model.Thread.Text,
                    Picture = UploadImage(model.Picture),
					Created = DateTime.Now.ToString()
				};

				_dbService.AddThread(newThread);

				return RedirectToAction("Index", "Home");
			}
			return View();
		}

		public string UploadImage(IFormFile Picture)
		{
			if (Picture == null)
			{
				return "http://placehold.it/500x500";
			}

			var uploadFolder = "uploads";
			var uploads = Path.Combine(_environment.WebRootPath, uploadFolder);

			using (var fileStream = new FileStream(Path.Combine(uploads, Picture.FileName), FileMode.Create))
			{
				Picture.CopyTo(fileStream);
			}

			return string.Concat(uploadFolder, "/", Picture.FileName);
		}

	}
}

forum/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

using forum.Services;
using forum.Models.ViewModels;
using forum.Models;
using forum.Data;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;

namespace forum.Controllers
{
    public class UserController : Controller
    {
		private readonly ForumContext _context;
		private readonly IDBService _dbService;

		public UserController(IDBService dbService, ForumContext context)
		{
			_dbService = dbService;
			_context = context;
		}
      
        public IActionResult Index()
        {
            return View();
        }

		[HttpPost]
		public IActionResult CreateUser(UsersViewModel model)
		{

            /* var newUser = new User()
            {
                Username = model.Username,
                Password = model.Password
            }; 

            _dbService.AddUser(newUser);

            TempData["userMessage"] = "User created!";*/


			return RedirectToAction("Index");
		}
    }
}

forum/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

forum/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

forum/Views/Home/Index.cshtml
@model forum.Models.ViewModels.ThreadsViewModel
@using System.Security.Claims

@{
    ViewData["Title"] = "Home Page";
}

<div class="list-container">
	<div class="row">
	<div class="col-md-6">
		<div class="list">

			@if (User.Identity.IsAuthenticated)
			{
			     <a asp-controller="Thread" asp-action="AddThread">
	                <div class="create-thread">
	                    <img src="@Model.Person.Picture" alt="@Model.Person.UserName" />
	                    <h5>Create New Thread</h5>
	                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
	                </div>
	             </a>
			} else {
                    <div class="create-thread">
                        <img src="https://upload.wikimedia.org/wikipedia/commons/5/59/Empty.png" alt="" style="background: #3f4f59"/>
                        <h5>Log in to create a new thread</h5>
                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                    </div>
			}
            
			@foreach(var thread in Model.Threads){
			    <div class="thread-latest">
                    <div class="thread-top">
					    <img src="@thread.Person.Picture" alt="" />
					    <h5 style="font-weight: 400">@thread.Person.UserName</h5>
				    </div>
				    <div class="thread-middle">
					    <h4>@thread.Subject</h4>
                        <p>@thread.Text</p>
					    <img src="@thread.Picture" alt="@thread.Picture" />
                    </div>
				    <hr />
				    <div class="thread-bottom">
					    <a asp-controller="Thread" asp-action="GetThread" asp-route-id="@thread.ID"><h5>Read more</h5></a>
					    <!--<a asp-controller="Thread" asp-action="GetThread" asp-route-id="@thread.ID"><h5>Model.Posts.Where(i => i.ThreadID == thread.ID).Count()</h5></a>-->
					    <!--<div> 7 &nbsp;<span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span></div>-->
                    </div>
			    </div>
			}
		</div>
	</div>
	
	<div class="col-md-6">
		<div class="list">
			<h6>Recent posts</h6>
            @foreach(var post in Model.Posts.Take(2)){
                <div class="thread-latest">
                    <div class="thread-top">
                        <img src="@post.Person.Picture" alt="" />
                        <h5 style="font-weight: 400">@post.Person.UserName said: "@post.Text"</h5>
						<p>@post.Created</p>
                    </div>
                    <div class="thread-middle"><br />
                    </div>
                </div>
            }

			<br />
			<h6>Recently joined users</h6>
			 @foreach(var user in Model.People.Take(2)){
                <div class="thread-latest thread--recently-users">
                    <div class="thread-top">
                        <img src="@user.Picture" alt="" />
                        <h5 style="font-weight: 400">@user.UserName</h5>
					    <p>@user.Joined</p>
                    </div>
                </div>
            }
			
		</div>
    </div>
	</div>	
</div>

forum/Views/Home/Login.cshtml
@model forum.Models.ViewModels.LoginViewModel
@{
    ViewData["Title"] = "Home Page";
}

<form asp-controller="Home" asp-action="Login" method="post">
	<label for="Username"></label>
    Username:  <input asp-for="Username" /> <br />
	<label for="Password"></label>
    Password: <input asp-for="Password" /><br />
    <button type="submit">Login</button>
</form>

forum/Views/Home/Register.cshtml
@model forum.Models.ViewModels.RegisterViewModel

@{
    ViewData["Title"] = "Home Page";
}
<br />
<a asp-controller="Home" asp-action="Index">Back</a><br /><br />

<form asp-controller="Home" asp-action="Register" method="post" enctype="multipart/form-data">
    Username:  <input asp-for="Username" /> <br />
    Password: <input asp-for="Password" /><br />
	Confirm Password: <input asp-for="ConfirmPassword" /><br /><br/>
	<div class="form-group">
        <input type="file" name="Picture" asp-for="Picture">
        <p class="help-block">Upload a picture</p>
    </div>
	
    <button type="submit">Register</button>
</form>

<h1>@TempData["path"]</h1>

forum/Views/Home/Sidenav.cshtml
@{
    ViewData["Title"] = "Home Page";
}

   <div class="col-sm-3 col-md-2 sidebar">
	<h3 class="sidebar-title"><a asp-controller="Home" asp-action="Index">Forum</a></h3>
      <ul class="nav nav-sidebar">
        <li class="active"><a asp-controller="Thread" asp-action="Index">Discussions</a></li>
        <li><a href="#">Sign in</a></li>
        <li><a asp-controller="User" asp-action="Index">Register</a></li>
      </ul>
    </div>
